<a href="https://colab.research.google.com/github/alantang1369/TensorFlow_Cert_Prep_2024/blob/main/_00_Tensorflow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [3]:
#create a scalar
scalar = tf.constant(8)


In [4]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [6]:
vector = tf.constant([1, 2, 3])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [7]:
matrix = tf.constant([[1, 2],
                      [3, 4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [8]:
tensor = tf.constant([
                      [
                          [1, 2, 3],
                          [3, 4, 5],
                          [6, 7, 8]
                       ],
                       [
                          [10, 11, 12],
                          [13, 14, 15],
                          [16, 17, 18]
                        ]
                      ])
tensor

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
print(f'The shape of the tensor: {tensor.shape}')
print(f'The size of the tensor: {tf.size(tensor)}')
print(f'The rank of the tensor: {tf.rank(tensor)}')

The shape of the tensor: (2, 3, 3)
The size of the tensor: 18
The rank of the tensor: 3


In [12]:
tf.random.set_seed(42)
tensor_1 = tf.random.uniform(shape=(5, 300))
tensor_2 = tf.random.uniform(shape=(5, 300))

In [13]:
tensor_1, tensor_1.shape, tensor_2, tensor_2.shape

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
         0.03699052],
        [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
         0.2200619 ],
        [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
         0.00726748],
        [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
         0.9409125 ],
        [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
         0.44135118]], dtype=float32)>,
 TensorShape([5, 300]),
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.828

In [17]:
result_vector = tf.matmul(tensor_1, tf.transpose(tensor_2))

In [18]:
result_vector, result_vector.shape

(<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[80.33345 , 73.40498 , 77.159615, 73.98369 , 80.90053 ],
        [75.146355, 68.80437 , 74.24302 , 71.841835, 75.60206 ],
        [79.7594  , 75.644554, 77.797585, 74.74873 , 80.559845],
        [75.08526 , 69.064064, 74.30776 , 72.27616 , 76.05669 ],
        [85.05688 , 74.26627 , 78.00687 , 74.88679 , 83.13417 ]],
       dtype=float32)>,
 TensorShape([5, 5]))

In [21]:
result_vector_2 = tf.tensordot(tensor_1, tf.transpose(tensor_2), axes=1)
result_vector_2

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33345 , 73.40498 , 77.159615, 73.98369 , 80.90053 ],
       [75.146355, 68.80437 , 74.24302 , 71.841835, 75.60206 ],
       [79.7594  , 75.644554, 77.797585, 74.74873 , 80.559845],
       [75.08526 , 69.064064, 74.30776 , 72.27616 , 76.05669 ],
       [85.05688 , 74.26627 , 78.00687 , 74.88679 , 83.13417 ]],
      dtype=float32)>

In [23]:
tf.equal(result_vector, result_vector_2)

<tf.Tensor: shape=(5, 5), dtype=bool, numpy=
array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])>

In [26]:
big_tensor = tf.random.uniform(shape=[224, 224, 3], seed=42),
big_tensor

(<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
 array([[[0.4163028 , 0.26858163, 0.47968316],
         [0.36457133, 0.95471144, 0.9418646 ],
         [0.61483395, 0.35842144, 0.5936024 ],
         ...,
         [0.3001454 , 0.7371932 , 0.9997108 ],
         [0.6578264 , 0.79280615, 0.1523186 ],
         [0.18333101, 0.84532166, 0.66058433]],
 
        [[0.99603903, 0.74609745, 0.5254276 ],
         [0.97391105, 0.12732589, 0.33558083],
         [0.15509152, 0.3798263 , 0.02595055],
         ...,
         [0.24695694, 0.4792341 , 0.907869  ],
         [0.93202424, 0.21663308, 0.3452747 ],
         [0.01570225, 0.97835445, 0.10668027]],
 
        [[0.216218  , 0.02733779, 0.2472924 ],
         [0.56103206, 0.02278149, 0.83240056],
         [0.8430499 , 0.86110675, 0.39599562],
         ...,
         [0.51704574, 0.2421813 , 0.6224375 ],
         [0.52620804, 0.409366  , 0.84243226],
         [0.5460491 , 0.18278158, 0.9165064 ]],
 
        ...,
 
        [[0.74593174, 0.8235165 

In [36]:
tf.random.set_seed(42)
big_tensor_1 = tf.random.uniform(shape=[224, 224, 3])
big_tensor_1

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.6645621 , 0.44100678, 0.3528825 ],
        [0.46448255, 0.03366041, 0.68467236],
        [0.74011743, 0.8724445 , 0.22632635],
        ...,
        [0.42612267, 0.09686017, 0.16105258],
        [0.1487099 , 0.04513884, 0.9497483 ],
        [0.4393103 , 0.28527975, 0.96971095]],

       [[0.73308516, 0.5657046 , 0.33238935],
        [0.8838178 , 0.87544763, 0.56711245],
        [0.8879347 , 0.47661996, 0.42041814],
        ...,
        [0.7716515 , 0.9116473 , 0.3229897 ],
        [0.43050945, 0.83253574, 0.45549798],
        [0.29816985, 0.9639522 , 0.3316357 ]],

       [[0.41132426, 0.2179662 , 0.53570235],
        [0.5112119 , 0.6484759 , 0.8894886 ],
        [0.42459428, 0.20189774, 0.85781324],
        ...,
        [0.02888799, 0.3995477 , 0.11355484],
        [0.68524575, 0.04945195, 0.17778492],
        [0.97627187, 0.79811585, 0.9411576 ]],

       ...,

       [[0.9019445 , 0.27011132, 0.8090267 ],
        [0.32

In [38]:
print(f'Maximum value: {tf.reduce_max(big_tensor)}')
print(f'Minimum value: {tf.reduce_min(big_tensor)}')

Maximum value: 0.9999901056289673
Minimum value: 1.7404556274414062e-05


In [40]:
unsqueezed_tensor = tf.random.Generator.from_seed(42)
unsqueezed_tensor = unsqueezed_tensor.normal(shape=[1, 224, 224, 3])


In [41]:
print(f'The shape before squeezing: {unsqueezed_tensor.shape}')
squeezed_tensor = tf.squeeze(unsqueezed_tensor)
print(f'The shape after squeezing: {squeezed_tensor.shape}')

The shape before squeezing: (1, 224, 224, 3)
The shape after squeezing: (224, 224, 3)


In [65]:
import numpy as np
ten_tensor = tf.constant(np.random.randint(10, size=10))
ten_tensor

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([7, 5, 0, 4, 1, 9, 3, 2, 3, 4])>

In [66]:
max_index = tf.math.argmax(ten_tensor)
ten_tensor[max_index]

<tf.Tensor: shape=(), dtype=int64, numpy=9>

In [67]:
tf.one_hot(tf.cast(ten_tensor,dtype=tf.int32), depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32)>